# Generated by Django 3.0.3 on 2020-02-14 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Task name')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('status', models.CharField(max_length=30, verbose_name='Task status')),
                ('file', models.FileField(blank=True, null=True, upload_to='', verbose_name='Attach file')),
            ],
        ),
    ]
